---
{{- with .Values.controller }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .fullname }}-environment
type: Opaque
stringData:
  {{- with .environment }}
  POSTGRES_URI: {{ .POSTGRES_URI }}
  DID_NAMESPACE: {{ .DID_NAMESPACE }}
  TRACTION_API_KEY: {{ .TRACTION_API_KEY }}
  TRACTION_TENANT_ID: {{ .TRACTION_TENANT_ID }}
  TRACTION_API_ENDPOINT: {{ .TRACTION_API_ENDPOINT }}
  TRACEABILITY_CONTROLLER_DOMAIN: {{ .TRACEABILITY_CONTROLLER_DOMAIN }}
  VERIFIER_ENDPOINT: {{ .VERIFIER_ENDPOINT }}
  {{- end }}
{{- end }}