---
{{- with .Values.controller }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .fullname }}
  annotations:
    kubernetes.io/ingress.class: {{ .ingress.className }}
spec:
  rules:
  - host: {{ .ingress.host }}
    http:
      paths:
      - backend:
          service:
            name: {{ .fullname }}
            port:
              number: {{ .service.apiPort }}
        path: /
        pathType: ImplementationSpecific
{{- end }}