{{- with .Values.controller }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .fullname }}-ingress
  labels:
    # certbot-managed: false
    {{- include "common.selectorLabels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include ".selectorLabels" . | nindent 6 }}
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              {{- include "common.tplvalues.render" (dict "value" .networkPolicy.ingress.namespaceSelector "context" $) | nindent 14 }}
        - podSelector:
            matchLabels:
              {{- include "common.tplvalues.render" (dict "value" .networkPolicy.ingress.podSelector "context" $) | nindent 14 }}
  policyTypes:
    - Ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ template "global.fullname" . }}
  labels:
    {{- include "common.selectorLabels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      'app.kubernetes.io/instance': {{ template "global.fullname" . }}
  ingress:
  - from:
    - podSelector:
        matchLabels:
          'app.kubernetes.io/instance': {{ template "global.fullname" . }}
{{- end }}