{{- with .Values.controller }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .fullname }}-ingress
  labels:
    # certbot-managed: false
    {{- toYaml $.Values.selectorLabels | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- toYaml .selectorLabels | nindent 6 }}
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              {{- toYaml .networkPolicy.ingress.namespaceSelector | nindent 14 }}
        - podSelector:
            matchLabels:
              {{- toYaml .networkPolicy.ingress.podSelector | nindent 14 }}
  policyTypes:
    - Ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ $.Values.fullname }}
  labels:
    {{- toYaml $.Values.selectorLabels | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      'app.kubernetes.io/instance': {{ $.Values.fullname }}
  ingress:
  - from:
    - podSelector:
        matchLabels:
          'app.kubernetes.io/instance': {{ $.Values.fullname }}
{{- end }}