{{- with .Values.controller }}{{- if .openshift.route.enabled -}}
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .fullname }}
  annotations:
    {{- toYaml .openshift.route.annotations | nindent 4 }}
  labels:
    {{- toYaml .labels | nindent 4 }}
spec:
  host: {{ .openshift.route.host | quote }}
  path: {{ .openshift.route.path }}
  to:
    kind: Service
    name: {{ .fullName }}
    weight: 100
  port:
    targetPort: {{ .service.apiPort }}
  wildcardPolicy: {{ .openshift.route.wildcardPolicy }}
  tls:
    {{- toYaml .openshift.route.tls | nindent 4}}
{{- end }}{{- end }}