{{- with .Values.controller }}{{- if .openshift.route.enabled -}}
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .fullname }}
  annotations:
    haproxy.router.openshift.io/timeout: {{ .openshift.route.timeout }}
  labels:
    {{- toYaml .labels | nindent 4 }}
spec:
  host: {{ .host | quote }}
  path: {{ .openshift.route.path }}
  to:
    kind: Service
    name: {{ .fullName }}
    weight: 100
  port:
    targetPort: {{ .openshift.route.targetPort }}
  wildcardPolicy: {{ .openshift.route.wildcardPolicy }}
  tls:
    {{- toYaml .openshift.route.tls | nindent 4}}
{{- end }}{{- end }}