{{- with .Values.controller }}{{- if .serviceAccount.create -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .serviceAccountName }}
  labels:
    {{- include "controller.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .serviceAccount.annotations | nindent 4 }}
{{- end }}{{- end }}