{{- with .Values.controller }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .fullname }}
  labels:
    {{- toYaml .labels | nindent 4 }}
spec:
  type: {{ .service.type }}
  selector:
    app: {{ .fullname }}
  ports:
    - port: {{ .service.apiPort }}
      targetPort: {{ .service.apiPort }}
      protocol: TCP
      name: api
{{- end }}