apiVersion: v1
kind: Service
metadata:
  name: {{ include "controller.fullname" . }}
  labels:
    {{- include "controller.labels" . | nindent 4 }}
spec:
  type: {{ .Values.controller.service.type }}
  selector:
    {{- include "controller.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.controller.service.adminPort }}
      targetPort: {{ .Values.controller.service.adminPort }}
      protocol: TCP
      name: api