---
version: '2'
services:

  traceability-api:
    build:
      context: .
    container_name: traceability-api
    restart: unless-stopped
    entrypoint: ["python", "main.py"]
    environment:
      WORKERS: ${WORKERS}
      PORT: ${PORT}
      TRACEABILITY_API_ENDPOINT: ${TRACEABILITY_API_ENDPOINT}
      TRACTION_API_URL: ${TRACTION_API_URL}
      TRACTION_TENANT_ID: ${TRACTION_TENANT_ID}
      TRACTION_API_KEY: ${TRACTION_API_KEY}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      JWT_SECRET: ${JWT_SECRET}
      JWT_ALGORITHM: ${JWT_ALGORITHM}
      VERIFIER_AGENT: ${VERIFIER_AGENT}
    labels:
      - traefik.enable=true
      - traefik.http.routers.traceability-api.rule=Host(`${TRACEABILITY_API_ENDPOINT}`)
      - traefik.http.routers.traceability-api.entrypoints=websecure
      - traefik.http.routers.traceability-api.tls.certresolver=myresolver
      - traefik.http.services.traceability-api.loadbalancer.server.port=${TRACEABILITY_API_PORT}

  redis:
    image: redis:7.2-alpine3.18
    container_name: redis
    privileged: true
    command: sh -c "./init.sh"
    restart: unless-stopped
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
      - ./configs/redis.conf:/usr/local/etc/redis/redis.conf
      - ./configs/redis_init.sh:/data/init.sh

  traefik:
    image: traefik:v2.10
    container_name: traefik
    restart: always
    security_opt:
      - no-new-privileges:true
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.websecure.address=:443
      - --certificatesresolvers.myresolver.acme.tlschallenge=true
      - --certificatesresolvers.myresolver.acme.email=${LETSENCRYPT_EMAIL}
      - --certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json
    ports:
      - 443:443
    volumes:
      - .letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
  redis_data:
