---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ $.Values.namespace }}
  name: {{ $.Values.name }}
  labels:
    app: {{ $.Values.name }}
spec:
  replicas: {{ $.Values.replicas }}
  selector:
    matchLabels:
      app: {{ $.Values.name }}
  template:
    metadata:
      labels:
        app: {{ $.Values.name }}
    spec:
      containers:
        - name: {{ $.Values.name }}
          image: {{ $.Values.image }}
          imagePullPolicy: Always
          ports:
            - containerPort: {{ $.Values.port }}
          envFrom:
            - secretRef:
                name: {{ $.Values.name }}