---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: {{ $.Values.namespace }}
  name: {{ $.Values.name }}
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: {{ $.Values.domain }}
    http:
      paths:
      - backend:
          service:
            name: {{ $.Values.name }}
            port:
              number: {{ $.Values.port }}
        path: /
        pathType: ImplementationSpecific