---
apiVersion: v1
kind: Service
metadata:
  namespace: {{ $.Values.namespace }}
  name: {{ $.Values.name }}
spec:
  type: LoadBalancer
  selector:
    app: {{ $.Values.name }}
  ports:
    - protocol: TCP
      port: {{ $.Values.port }}
      targetPort: {{ $.Values.port }}