---
namespace: traction-tenant-traceability-controller

agent:
  name: agent
  image: bcgovimages/aries-cloudagent:py3.9-indy-1.16.0_0.12.0rc2
  port: 8020
  replicas: 1

postgres:
  name: postgres
  image: postgres:16-alpine
  port: 5432
  replicas: 1
  environment:
    POSTGRES_USER: '${{ secrets.POSTGRES_USER }}'
    POSTGRES_PASSWORD: '${{ secrets.POSTGRES_PASSWORD }}'

controller:
  name: traction-tenant-traceability-controller
  image: '${{ variables.TRACEABILITY_CONTROLLER_IMAGE }}'
  port: 8000
  replicas: 1
  domain: '${{ variables.TRACEABILITY_CONTROLLER_DOMAIN }}'
  environment:
    PORT: 8000
    WORKERS: 4
    TRACEABILITY_CONTROLLER_DOMAIN: '${{ variables.TRACEABILITY_CONTROLLER_DOMAIN }}'
    POSTGRES_URI: '${{ secrets.POSTGRES_URI }}'
    TRACTION_API_KEY: '${{ secrets.TRACTION_API_KEY }}'
    TRACTION_TENANT_ID: '${{ secrets.TRACTION_TENANT_ID }}'
    TRACTION_API_ENDPOINT: '${{ variables.TRACTION_API_ENDPOINT }}'