{{- with .Values.acapy }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .fullname }}-ingress
  labels:
    {{- toYaml .labels | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- toYaml .selectorLabels | nindent 6 }}
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              {{- toYaml .networkPolicy.ingress.namespaceSelector | nindent 14 }}
        - podSelector:
            matchLabels:
              {{- toYaml .networkPolicy.ingress.podSelector | nindent 14 }}
  policyTypes:
    - Ingress
{{- end }}