{{- with .Values.acapy }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .fullname }}-ingress
  labels:
    {{- include "acapy.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "acapy.selectorLabels" . | nindent 6 }}
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              {{- include "common.tplvalues.render" (dict "value" .networkPolicy.ingress.namespaceSelector "context" $) | nindent 14 }}
        - podSelector:
            matchLabels:
              {{- include "common.tplvalues.render" (dict "value" .networkPolicy.ingress.podSelector "context" $) | nindent 14 }}
  policyTypes:
    - Ingress
{{- end }}