{{- with .Values.acapy }}{{- if .serviceAccount.create -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .serviceAccountName }}
  labels:
    {{- toYaml .labels | nindent 4 }}
  annotations:
    {{- toYaml .serviceAccount.annotations | nindent 4 }}
{{- end }}{{- end }}